from django.urls import path
from .views.transaction_views import (
    category_report,
    profit_loss_report,
    profit_loss_content,
    transaction_list,
    transaction_table,
    transaction_bulk_action,
    transaction_delete,
    transaction_update,
    transaction_transfer_matches,
    transaction_transfer_pair,
    transfer_list,
    transfer_unpair,
)
from .views.category_views import (
    category_list,
    category_table,
    category_create,
    category_update,
    category_delete,
)
from .views.vendor_views import (
    vendor_list,
    vendor_table,
    vendor_create,
    vendor_update,
    vendor_delete,
)
from .views.sales_views import (
    sales_transactions_list,
    sales_invoice_create,
    sales_invoice_edit,
    sales_invoice_detail,
    sales_invoice_match_apply,
    sales_invoice_payment_delete,
    sales_invoice_matches,
)
from .views.import_views import (
    account_imports,
    import_commit,
    import_review,
    import_rollback,
    import_delete,
    import_stage,
)
from .views.accounts_views import (
    account_list,
    account_create,
    account_table,
    account_archive,
    account_delete,
    account_update,
)

app_name = "fincore"

urlpatterns = [
    path("transactions/", transaction_list, name="transaction_list"),
    path("transactions/table/", transaction_table, name="transaction_table"),
    path("transactions/bulk-action/", transaction_bulk_action, name="transaction_bulk_action"),
    path("transactions/<int:pk>/delete/", transaction_delete, name="transaction_delete"),
    path("transactions/update/", transaction_update, name="transaction_update"),
    path("transactions/transfer/matches/", transaction_transfer_matches, name="transaction_transfer_matches"),
    path("transactions/transfer/pair/", transaction_transfer_pair, name="transaction_transfer_pair"),
    path("transfers/", transfer_list, name="transfer_list"),
    path("transfers/<int:group_id>/unpair/", transfer_unpair, name="transfer_unpair"),
    path("reports/profit-loss/", profit_loss_report, name="profit_loss_report"),
    path("reports/profit-loss/content/", profit_loss_content, name="profit_loss_content"),
    path("sales/transactions/", sales_transactions_list, name="sales_transactions_list"),
    path("sales/transactions/new/", sales_invoice_create, name="sales_invoice_create"),
    path("sales/transactions/<int:invoice_id>/edit/", sales_invoice_edit, name="sales_invoice_edit"),
    path("sales/transactions/<int:invoice_id>/", sales_invoice_detail, name="sales_invoice_detail"),
    path("sales/transactions/matches/", sales_invoice_matches, name="sales_invoice_matches"),
    path("sales/transactions/match/", sales_invoice_match_apply, name="sales_invoice_match_apply"),
    path("sales/transactions/payment/<int:payment_id>/delete/", sales_invoice_payment_delete, name="sales_invoice_payment_delete"),
    path("categories/", category_list, name="category_list"),
    path("categories/table/", category_table, name="category_table"),
    path("categories/create/", category_create, name="category_create"),
    path("categories/update/", category_update, name="category_update"),
    path("categories/<int:pk>/report/", category_report, name="category_report"),
    path("categories/<int:pk>/delete/", category_delete, name="category_delete"),
    path("vendors/", vendor_list, name="vendor_list"),
    path("vendors/table/", vendor_table, name="vendor_table"),
    path("vendors/create/", vendor_create, name="vendor_create"),
    path("vendors/update/", vendor_update, name="vendor_update"),
    path("vendors/<int:pk>/delete/", vendor_delete, name="vendor_delete"),
    path("imports/stage/", import_stage, name="import_stage"),
    path("accounts/<int:account_id>/imports/", account_imports, name="account_imports"),
    path("imports/<int:batch_id>/review/", import_review, name="import_review"),
    path("imports/<int:batch_id>/commit/", import_commit, name="import_commit"),
    path("imports/<int:batch_id>/rollback/", import_rollback, name="import_rollback"),
    path("imports/<int:batch_id>/delete/", import_delete, name="import_delete"),
    path("accounts/", account_list, name="account_list"),
    path("accounts/table/", account_table, name="account_table"),
    path("accounts/create/", account_create, name="account_create"),
    path("accounts/update/", account_update, name="account_update"),
    path("accounts/<int:pk>/archive/", account_archive, name="account_archive"),
    path("accounts/<int:pk>/delete/", account_delete, name="account_delete"),
]
