# Generated by Django 5.2.9 on 2026-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payee',
            field=models.CharField(blank=True, help_text='Other party involved; free text; direction determined by kind/amount.', max_length=255),
        ),
    ]
