# Generated by Django 5.2.9 on 2026-01-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincore', '0002_transaction_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Archive instead of delete. Inactive accounts stay in history but are not selectable for new activity.'),
        ),
    ]
