# Generated by Django 5.2.9 on 2026-02-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fincore", "0012_invoice_invoiceitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="fincore.invoice",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_payments",
                        to="fincore.transaction",
                    ),
                ),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name="invoicepayment",
            constraint=models.UniqueConstraint(
                fields=("invoice", "transaction"),
                name="uniq_invoice_transaction_payment",
            ),
        ),
    ]

