# Generated by Django 5.2.9 on 2026-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fincore", "0013_invoice_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("partially_paid", "Partially paid"),
                    ("paid", "Paid"),
                    ("void", "Void"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]

